# Generated by Django 2.2.5 on 2019-10-09 13:14

from django.db import migrations, models
import mod.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='hay', max_length=240)),
                ('user_name', models.CharField(default='zain', max_length=30)),
                ('email', models.CharField(default='zain@gmail.com', max_length=40)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('publish', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('private', 'Private')], default='draft', max_length=120)),
                ('view_count', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('auther_email', models.CharField(blank=True, max_length=240, null=True, validators=[mod.validator.valid_email])),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
